### ISSUE TITLE
Config should be left to the ODC

### ISSUE THREAD

**Issue by alexgleith** [MartinPontius/pygeoapi-odc-provider#3]
The code here https://github.com/MartinPontius/pygeoapi-odc-provider/blob/master/odcprovider/odcprovider.py#L67 around finding the configuration file for the ODC doesn't allow a user to configure the ODC using environment variables, which is a widely used way of configuration.

It'd be best to ignore configuration for this project, and just let the ODC do it.

**Comment by EHJ-52n** [comment]
Hi @alexgleith ,
I understand your point and I am unclear what you mean be "[...] just let the ODC do it."?

Could you give some more details, please.

**Comment by alexgleith** [comment]
See https://github.com/MartinPontius/pygeoapi-odc-provider/pull/4, which simplifies things.

Nice work on putting the provider together, by the way!
