### ISSUE TITLE
Check bbox of catalog items for API Records

### ISSUE THREAD

**Issue by MartinPontius** [MartinPontius/pygeoapi-odc-provider#7]
The bbox doesn't look correct for some example data. 
A problem could be here: https://github.com/MartinPontius/pygeoapi-odc-provider/blob/feature/ogc-api-records/odcprovider/utils.py

**Comment by EHJ-52n** [comment]
Fixed by https://github.com/MartinPontius/pygeoapi-odc-provider/commit/b75970563283b4f9c2419b06d48e8cc875d04fc7
